import { Routes } from '@angular/router';

import { Base64Component } from './ferramentas/base64/base64.component';
import { EditorJsonComponent } from './ferramentas/editor-json/editor-json.component';
import { VisualizadorJwtComponent } from './ferramentas/visualizador-jwt/visualizador-jwt.component';
import { VisualizadorJweComponent } from './ferramentas/visualizador-jwe/visualizador-jwe.component';
import { UrlcodecComponent } from './ferramentas/urlcodec/urlcodec.component';
import { ConversorImagemTextoOcrComponent } from './ferramentas/conversor-imagem-texto-ocr/conversor-imagem-texto-ocr.component';
import { UnixTimestampComponent } from './ferramentas/unix-timestamp/unix-timestamp.component';
import { TextoQrcodeComponent } from './ferramentas/texto-qrcode/texto-qrcode.component';
import { QuebraLinhaComponent } from './ferramentas/quebra-linha/quebra-linha.component';
import { TextoGlobalComponent } from './ferramentas/texto-global/texto-global.component';
import { TemplateDeTextoComponent } from './ferramentas/template-de-texto/template-de-texto.component';
import { VisualizadorX509Component } from './ferramentas/visualizador-x-509/visualizador-x-509.component';
import { GeradorCertificadoX509Component } from './ferramentas/gerador-certificado-x509/gerador-certificado-x509.component';
import { HomeComponent } from './home/home.component';
import { SobreComponent } from './sobre/sobre.component';
import { JuntadorPdfComponent } from './ferramentas/juntador-pdf/juntador-pdf.component';
import { SeparadorPdfComponent } from './ferramentas/separador-pdf/separador-pdf.component';
import { GeradorHashComponent } from './ferramentas/gerador-hash/gerador-hash.component';
import { DiffTextoComponent } from './ferramentas/diff-texto/diff-texto.component';
import { GeradorUuidComponent } from './ferramentas/gerador-uuid/gerador-uuid.component';
import { GeradorSenhaComponent } from './ferramentas/gerador-senha/gerador-senha.component';
import { GeradorHmacComponent } from './ferramentas/gerador-hmac/gerador-hmac.component';
import { GeradorCpfCnpjComponent } from './ferramentas/gerador-cpf-cnpj/gerador-cpf-cnpj.component';
import { ComparadorJsonYamlComponent } from './ferramentas/comparador-json-yaml/comparador-json-yaml.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'sobre', component: SobreComponent },
  { path: 'base64', component: Base64Component },
  { path: 'editor-json', component: EditorJsonComponent },
  { path: 'visualizador-jwt', component: VisualizadorJwtComponent },
  { path: 'visualizador-jwe', component: VisualizadorJweComponent },
  { path: 'codec-de-url', component: UrlcodecComponent },
  { path: 'conversor-imagem-texto-ocr', component: ConversorImagemTextoOcrComponent },
  { path: 'unix-timestamp', component: UnixTimestampComponent },
  { path: 'texto-qrcode', component: TextoQrcodeComponent },
  { path: 'quebra-linha', component: QuebraLinhaComponent },
  { path: 'texto-global', component: TextoGlobalComponent },
  { path: 'texto-global/:grupo/:canal', component: TextoGlobalComponent },
  { path: 'template-de-texto', component: TemplateDeTextoComponent },
  { path: 'visualizador-x-509', component: VisualizadorX509Component },
  { path: 'gerador-certificado-x509', component: GeradorCertificadoX509Component },
  { path: 'juntador-pdf', component: JuntadorPdfComponent },
  { path: 'separador-pdf', component: SeparadorPdfComponent },
  { path: 'gerador-hash', component: GeradorHashComponent },
  { path: 'diff-texto', component: DiffTextoComponent },
  { path: 'gerador-uuid', component: GeradorUuidComponent },
  { path: 'gerador-senha', component: GeradorSenhaComponent },
  { path: 'gerador-hmac', component: GeradorHmacComponent },
  { path: 'gerador-cpf-cnpj', component: GeradorCpfCnpjComponent },
  { path: 'comparador-json-yaml', component: ComparadorJsonYamlComponent },
];
