# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ferramentasdev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar versão do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalar angular CLI
        run: npm install -g @angular/cli

      - name: Instalar dependencias do projeto
        run: npm install
      
      - name: Build do projeto angular para producao
        run: ng build --configuration production

      - name: Zipar artefato para deploy
        run: zip release.zip ./* -r

      - name: Upload de artefato para job de deploy
        uses: actions/upload-artifact@v3
        with:
          name: ferramentas
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download do artefato do job de build
        uses: actions/download-artifact@v3
        with:
          name: ferramentas

      - name: Descompactando artefato para deploy
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E836BC20B3304C41A9F00335A2DEAC51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42517BC39A9A4629BD1D47562DAB4B52 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61A113B58C10490A97BBF2C63942B4E0 }}

      - name: 'Deploy no Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ferramentasdev'
          slot-name: 'Production'
          package: .
          